name: Build & Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0 # god thank you AhsanAyaz
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        base_href: /idle-game-save-editor/ 
        deploy_branch: gh-pages 
        angular_dist_build_folder: dist/idle-game-save-editor/browser

permissions:
  contents: write 
